export const ADD_LABEL_REQUEST = "ADD_LABEL_REQUEST"
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS"
export const ADD_LABEL_FAILURE = "ADD_LABEL_FAILURE"

export const READ_LABELS_REQUEST="READ_LABELS_REQUEST"
export const READ_LABELS_SUCCESS="READ_LABELS_SUCCESS"
export const READ_LABELS_FAILURE="READ_LABELS_FAILURE"

export const STOP_WATCH_SESSION_REQUEST = "STOP_WATCH_SESSION_REQUEST"
export const STOP_WATCH_SESSION_SUCCESS = "STOP_WATCH_SESSION_SUCCESS"
export const STOP_WATCH_SESSION_FAILURE = "STOP_WATCH_SESSION_FAILURE"